# Generated by Django 2.0.5 on 2019-01-26 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('nivel', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('tiempo', models.TimeField(auto_now_add=True, null=True)),
                ('fechahora', models.DateTimeField(auto_now_add=True, null=True)),
                ('texto', models.CharField(blank=True, max_length=10000, null=True)),
                ('visto', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destacamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('iglesia', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('pastor', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('tel_pastor', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('comandante_mayor', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('tel_comandante', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('direccion_GPS', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('foto', models.ImageField(blank=True, max_length=1000, null=True, upload_to='')),
                ('activo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('tiempo', models.TimeField(auto_now_add=True, null=True)),
                ('fechahora', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenDestacamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='avatares/usuario.png', upload_to='avatares')),
                ('destacamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eres.Destacamento')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=500, null=True)),
                ('primer_nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=500, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=500, null=True)),
                ('sexo', models.CharField(blank=True, max_length=500, null=True)),
                ('telefono', models.CharField(blank=True, max_length=500, null=True)),
                ('direccion', models.CharField(blank=True, max_length=500, null=True)),
                ('direccion_GPS', models.CharField(blank=True, max_length=500, null=True)),
                ('dia', models.IntegerField(blank=True, null=True)),
                ('mes', models.CharField(blank=True, max_length=500, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, default='static/imagenes/usuario.png', null=True, upload_to='avatares')),
                ('activo', models.BooleanField(default=True)),
                ('departamento', models.CharField(blank=True, max_length=500, null=True)),
                ('destacamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eres.Destacamento')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eres.Cargos')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eres.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('tiempo', models.TimeField(auto_now_add=True, null=True)),
                ('fechahora', models.DateTimeField(auto_now_add=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=10000, null=True)),
                ('vistas', models.IntegerField(blank=True, null=True)),
                ('comentarios', models.IntegerField(blank=True, null=True)),
                ('favoritos', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='favorito',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eres.Publicacion'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='destacamento',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eres.Zona'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eres.Publicacion'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
