# Generated by Django 2.0.5 on 2018-12-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eres', '0002_auto_20181223_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
