# Generated by Django 2.0.5 on 2018-12-29 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eres', '0004_auto_20181224_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('codigo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destacamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('iglesia', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('pastor', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('direccion_GPS', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('foto', models.ImageField(blank=True, max_length=1000, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenDestacamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='avatares/usuario.png', upload_to='avatares')),
                ('destacamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eres.Destacamento')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='avatares/usuario.png', upload_to='avatares')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=500, null=True)),
                ('primer_nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=500, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=500, null=True)),
                ('sexo', models.CharField(blank=True, max_length=500, null=True)),
                ('telefono', models.CharField(blank=True, max_length=500, null=True)),
                ('direccion', models.CharField(blank=True, max_length=500, null=True)),
                ('direccion_GPS', models.CharField(blank=True, max_length=500, null=True)),
                ('dia', models.IntegerField(blank=True, null=True)),
                ('mes', models.CharField(blank=True, max_length=500, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, max_length=1000, null=True, upload_to='')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eres.Cargos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='imagenperfil',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eres.Perfil'),
        ),
    ]
