# Generated by Django 2.0.5 on 2019-01-02 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eres', '0005_auto_20181229_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='destacamento',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eres.Zona'),
        ),
    ]
