# Generated by Django 2.0.5 on 2019-01-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eres', '0006_destacamento_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargos',
            name='nivel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
