# Generated by Django 2.0.5 on 2019-01-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eres', '0007_cargos_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargos',
            name='usado',
            field=models.BooleanField(default=False),
        ),
    ]
