# Generated by Django 2.0.5 on 2019-01-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eres', '0013_auto_20190108_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='static/imagenes/usuario.png', null=True, upload_to='avatares'),
        ),
    ]
