# Generated by Django 2.0.5 on 2019-01-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eres', '0014_auto_20190108_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
