# Generated by Django 2.0.5 on 2019-01-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eres', '0015_perfil_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='departamento',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
