# Generated by Django 2.0.5 on 2019-01-16 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eres', '0016_perfil_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('tiempo', models.TimeField(auto_now_add=True, null=True)),
                ('fechahora', models.DateTimeField(auto_now_add=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=10000, null=True)),
                ('vistas', models.IntegerField(blank=True, null=True)),
                ('comentarios', models.IntegerField(blank=True, null=True)),
                ('favoritos', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
