# Generated by Django 2.0.5 on 2019-01-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eres', '0017_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
