# Generated by Django 2.0.5 on 2019-01-25 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eres', '0019_comentario_favorito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargos',
            name='usado',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='cargo',
        ),
        migrations.AddField(
            model_name='cargos',
            name='perfil',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='eres.Perfil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='visto',
            field=models.BooleanField(default=True),
        ),
    ]
