# Generated by Django 2.0.5 on 2019-01-25 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eres', '0020_auto_20190125_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='cargos',
            name='perfil',
        ),
        migrations.AddField(
            model_name='permisos',
            name='cargos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eres.Cargos'),
        ),
        migrations.AddField(
            model_name='permisos',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eres.Perfil'),
        ),
    ]
