# Generated by Django 2.0.5 on 2019-01-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eres', '0021_auto_20190125_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='destacamento',
            name='comandante_mayor',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='destacamento',
            name='tel_comandante',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='destacamento',
            name='tel_pastor',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
