# Generated by Django 2.0.5 on 2019-01-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eres', '0022_auto_20190125_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='destacamento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
