# Generated by Django 2.0.5 on 2020-01-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eres', '0023_destacamento_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='nombre',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
